# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='portrait',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b'portrait'),
        ),
    ]
