# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face', models.ImageField(blank=True, default=None, null=True, upload_to='faceBook')),
                ('face_id', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FaceTempPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='faceTempPhoto')),
            ],
        ),
        migrations.CreateModel(
            name='Tempfaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_list', models.ManyToManyField(related_name='tempfaces', to='faceBook.Face')),
                ('temp_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceBook.FaceTempPhoto')),
            ],
        ),
    ]
