# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceBook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='age',
            field=models.FloatField(blank=True, default='18'),
        ),
        migrations.AddField(
            model_name='face',
            name='emotion',
            field=models.CharField(default='Undetected', max_length=50),
        ),
    ]
