# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceBook', '0002_auto_20170420_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='emotion',
            field=models.CharField(default='Undetected emotion', max_length=50),
        ),
    ]
